name: CD-Build

on:
  push:
    # Runs on all branches so they share a github.run_number increment
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/FileSystemAbstractions.sln
      
    - name: Build FileSystemAbstractions
      run: dotnet build src/FileSystemAbstractions/FileSystemAbstractions.csproj -c Release --no-restore -f netstandard2.0
      
      # packs all nuget packages at once 
    - name: Pack FileSystemAbstractions Nuget Alpha
      run: dotnet pack src/FileSystemAbstractions/FileSystemAbstractions.csproj -c Release --no-build -p:PackageVersion=0.0.${{github.run_number}}-alpha
    - name: Pack FileSystemAbstractions Nuget
      run: dotnet pack src/FileSystemAbstractions/FileSystemAbstractions.csproj -c Release --no-build -p:PackageVersion=0.0.${{github.run_number}}
      
    - name: Publish FileSystemAbstractions Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Nugets
        path: src/**/bin/**/*.nupkg
        
  integration:
    needs: build
    name: Deploy Nuget-alpha packages
    environment:
      name: Integration
    runs-on: ubuntu-latest
    steps:
    - name: Download nugets
      uses: actions/download-artifact@v2
      with:
        name: Nugets
      
      
    - name: Display structure of downloaded files
      run: ls -R
    - name: Push FileSystemAbstractions Nuget
      run: dotnet nuget push ./FileSystemAbstractions/bin/Release/FileSystemAbstractions.0.0.${{github.run_number}}-alpha.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json

  production:
    needs: integration
    name: Deploy Nuget packages to production
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
    - name: Download nugets
      uses: actions/download-artifact@v2
      with:
        name: Nugets
        
    - name: Push FileSystemAbstractions Nuget
      run: dotnet nuget push ./FileSystemAbstractions/bin/Release/FileSystemAbstractions.0.0.${{github.run_number}}.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json
